### ISSUE TITLE
Fix path for saving/retrieving toonix avatar images

### ISSUE THREAD

**Issue by Juansecu** [Juansecu/OpenToonix-HTTP-Server#5]
Fix bug with **saving/retrieving toonix avatar images** _(when the application is deployed)_ by **changing the path of the folder where they are stored**.

**Comment by carloscardoso-prog** [comment]
How to run it?
please i really want to play this game

**Comment by Juansecu** [comment]
> How to run it?
> please i really want to play this game

Hi.

OpenToonix is not playable at the moment. Only register and login are working (with some changes from the original client).

Although, if you still want to set up the server, check out the README.md file.
